# Generated by Django 5.2.5 on 2025-08-28 19:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('event_short', models.CharField(blank=True, max_length=255, null=True)),
                ('event_tags', models.CharField(blank=True, max_length=255, null=True)),
                ('event_desc', models.CharField(max_length=500)),
                ('event_rules', models.TextField()),
                ('solo_or_group', models.CharField(default='', max_length=10)),
                ('min_members', models.IntegerField(default=1)),
                ('max_members', models.IntegerField(default=1)),
                ('prize_worth', models.CharField(max_length=255)),
                ('online', models.BooleanField(default=True)),
                ('image', models.ImageField(default='image_uploads/event_pics/event_default.png', upload_to='image_uploads/event_pics/')),
                ('showPeformanceLink', models.BooleanField(default=True)),
                ('portalUrl', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=127)),
                ('module_query_name_without_spaces_all_small', models.CharField(max_length=127)),
                ('module_icon', models.ImageField(default='image_uploads/moduleicons/module_icon_default.png', upload_to='image_uploads/moduleicons/')),
                ('module_icon_active', models.ImageField(default='image_uploads/moduleicons/active/module_icon_default.png', upload_to='image_uploads/moduleicons/active/')),
            ],
        ),
        migrations.CreateModel(
            name='CompTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team_name', models.CharField(default='undefined', max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_name1', to='competitions.competition')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_leader', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(to='users.teammembers')),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulename', to='competitions.module'),
        ),
        migrations.CreateModel(
            name='SubmitPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, max_length=2000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_name2', to='competitions.competition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compteams2', to='competitions.compteam')),
            ],
        ),
    ]
