# Generated by Django 5.2.5 on 2025-08-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='online',
        ),
        migrations.AddField(
            model_name='competition',
            name='event_mode',
            field=models.CharField(default='true', max_length=10),
        ),
    ]
