# Generated by Django 5.2.4 on 2025-08-28 18:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_participant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.AlterField(
            model_name='competition',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='competition',
            name='image',
            field=models.ImageField(default='image_uploads/event_pics/event_default.png', upload_to='image_uploads/event_pics/'),
        ),
        migrations.AlterField(
            model_name='compteam',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='module',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='module',
            name='module_icon',
            field=models.ImageField(default='image_uploads/moduleicons/module_icon_default.png', upload_to='image_uploads/moduleicons/'),
        ),
        migrations.AlterField(
            model_name='module',
            name='module_icon_active',
            field=models.ImageField(default='image_uploads/moduleicons/active/module_icon_default.png', upload_to='image_uploads/moduleicons/active/'),
        ),
        migrations.AlterField(
            model_name='submitperformance',
            name='link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
