# Generated by Django 5.2.4 on 2025-08-30 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_remove_competition_online_competition_event_mode'),
        ('competitions', '0003_delete_participant_alter_competition_id_and_more'),
    ]

    operations = [
    ]
