# Generated by Django 5.2.7 on 2025-10-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_merge_20250830_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='module_icon_active',
            field=models.ImageField(upload_to='image_uploads/moduleicons/active/'),
        ),
    ]
