# Generated by Django 5.2.5 on 2025-08-08 15:04

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fullname", models.CharField(max_length=150)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                (
                    "alternate_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=128)),
                (
                    "collegename",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=150, null=True)),
                ("state", models.CharField(blank=True, max_length=200, null=True)),
                ("otp", models.CharField(blank=True, max_length=6)),
                ("otp_created_at", models.DateTimeField(blank=True, null=True)),
                ("otp_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session_stage",
                    models.CharField(
                        choices=[
                            ("profile", "Profile"),
                            ("team", "Team"),
                            ("otp", "OTP"),
                        ],
                        default="profile",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamMembers",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("memberid", models.CharField(blank=True, max_length=255, unique=True)),
                (
                    "img",
                    models.ImageField(
                        default="user-default.png",
                        upload_to="image_uploads/userdp/%Y/%m/%d/",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(blank=True, max_length=150)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        default="M",
                        max_length=1,
                    ),
                ),
                ("collegename", models.CharField(max_length=150)),
                ("city", models.CharField(blank=True, max_length=150)),
                ("state", models.CharField(blank=True, max_length=200)),
                ("accommodation", models.BooleanField(default=False)),
                ("days_stay", models.IntegerField(default=0)),
                ("accommodation_type", models.CharField(default="none", max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name="NewUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        max_length=254,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=150, null=True, unique=True
                    ),
                ),
                ("provider", models.CharField(default="email", max_length=200)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                ("verified_email", models.BooleanField(default=False)),
                (
                    "password_reset_token",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("password_reset_expiry", models.DateTimeField(blank=True, null=True)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("fullname", models.CharField(max_length=150)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        default="M",
                        max_length=20,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("participant", "Participant"),
                            ("volunteer", "Volunteer"),
                            ("judge", "Judge"),
                            ("sponsor", "Sponsor"),
                            ("organizer", "Organizer"),
                        ],
                        default="participant",
                        max_length=20,
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        default="user-default.png",
                        upload_to="image_uploads/userdp/%Y/%m/%d/",
                    ),
                ),
                ("about", models.TextField(blank=True, max_length=500)),
                ("percentage_complete", models.IntegerField(default=0)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, unique=True
                    ),
                ),
                (
                    "alternate_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                (
                    "collegename",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=150, null=True)),
                ("state", models.CharField(blank=True, max_length=200, null=True)),
                ("alcherid", models.CharField(blank=True, max_length=255, unique=True)),
                ("referred_by", models.CharField(blank=True, max_length=255)),
                ("otp", models.CharField(default="000000", max_length=6)),
                ("otp_created_at", models.DateTimeField(blank=True, null=True)),
                ("otp_used", models.BooleanField(default=False)),
                ("team_members", models.IntegerField(default=0)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, related_name="newuser_set", to="auth.group"
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="newuser_permissions_set",
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "ordering": ["email"],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "accommodation",
                    models.CharField(
                        blank=True,
                        choices=[("Y", "Yes"), ("N", "No")],
                        default="N",
                        max_length=1,
                        null=True,
                    ),
                ),
                ("blankets", models.IntegerField(default=0)),
                ("dues", models.IntegerField(default=0)),
                ("total_paid", models.IntegerField(default=0)),
                (
                    "leader",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="teams", to="users.teammembers"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="users.team",
                    ),
                ),
            ],
        ),
    ]
