# Generated by Django 5.2.4 on 2025-09-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_registrationsession_pixel_highlight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationsession',
            name='pixel_highlight',
        ),
        migrations.AddField(
            model_name='newuser',
            name='pixel_highlight',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
