# Generated by Django 5.2.4 on 2025-09-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_team_members_teammembers_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammembers',
            name='team',
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='teams', to='users.teammembers'),
        ),
    ]
