# Generated by Django 5.2.6 on 2025-10-09 19:46

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_teammembers_team_team_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newuser",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None
            ),
        ),
        migrations.AlterField(
            model_name="newuser",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
