# Generated by Django 5.2.7 on 2025-10-14 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_newuser_phone_number_alter_newuser_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registrationsession",
            name="alternate_phone",
        ),
        migrations.RemoveField(
            model_name="registrationsession",
            name="city",
        ),
        migrations.RemoveField(
            model_name="registrationsession",
            name="collegename",
        ),
        migrations.RemoveField(
            model_name="registrationsession",
            name="email",
        ),
        migrations.RemoveField(
            model_name="registrationsession",
            name="fullname",
        ),
        migrations.RemoveField(
            model_name="registrationsession",
            name="password",
        ),
        migrations.RemoveField(
            model_name="registrationsession",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="registrationsession",
            name="state",
        ),
        migrations.RemoveField(
            model_name="registrationsession",
            name="username",
        ),
        migrations.AddField(
            model_name="registrationsession",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
