# Generated by Django 5.2.7 on 2025-10-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_registrationsession_alternate_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newuser",
            name="profile_pic_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
